/**
 * Component Data Formatters for @cl-mcp/mcp-server
 *
 * Transforms raw component metadata into formatted markdown responses
 * for each detail_level: api, full, examples, types.
 *
 * Parametric — no hardcoded library names or import paths.
 */

import { type StrictComponentAPI, buildStrictAPIFromAnalysis } from "../types.js";

/**
 * Sentinel rendered when a type-bearing field is `null` (schema v4.0).
 * Replaces the legacy `'unknown'` / `'void'` strings the analyzer used to
 * emit unconditionally. Surface this consistently so the LLM can recognize
 * an unresolved type rather than treating it as a real type name.
 */
const UNRESOLVED_TYPE = "<unresolved>";

function fmtType(t: string | null | undefined, resolved?: boolean): string {
  if (t === null || t === undefined) return UNRESOLVED_TYPE;
  return resolved === false ? `${t} (unresolved)` : t;
}
import { getLibraryConfig } from "../config.js";
import {
  buildSearchMetadataMap,
  countDirectivesAndPipes,
  extractSelectors,
  getAnalyzedEntry,
  getAvailableComponents,
  getComponentAnalysis,
  getPreloadedComponentMetadata,
} from "../data/metadata.js";
import type { FileAnalysis } from "../types.js";
import { resolveComponentName } from "./resolver.js";
import { type SearchResult, getSearchOptions, searchComponents } from "./search.js";

// ── Shared rendering helpers ────────────────────────────────────────

type DirectiveEntry = { analysis: FileAnalysis["directives"][0]; api: StrictComponentAPI };

function collectDirectives(analyses: readonly FileAnalysis[]): DirectiveEntry[] {
  const result: DirectiveEntry[] = [];
  for (const fileAnalysis of analyses) {
    for (const directive of fileAnalysis.directives || []) {
      if (!directive.metadata.selector) continue;
      result.push({ analysis: directive, api: buildStrictAPIFromAnalysis(directive) });
    }
  }
  return result;
}

function collectPipes(analyses: readonly FileAnalysis[]): FileAnalysis["pipes"] {
  const result: FileAnalysis["pipes"][number][] = [];
  for (const fileAnalysis of analyses) {
    result.push(...(fileAnalysis.pipes || []));
  }
  return result;
}

function getImportPath(componentName: string): string {
  const config = getLibraryConfig();
  if ((config.framework ?? "angular") === "react") {
    // React: root import of the (namespace) symbol — `Dialog.Root` is used
    // as `import { Dialog } from '<pkg>'` + `<Dialog.Root>`.
    const symbol = componentName.split(".")[0];
    return `import { ${symbol} } from '${config.packageName}';`;
  }
  return `import { ... } from '${config.packageName}/${componentName}';`;
}

/**
 * Binding examples are generated by the analyzer in Angular syntax
 * (`[name]="value"`, `(name)="handler($event)"`). For React libraries the
 * same information is rendered in JSX syntax instead.
 */
function frameworkizeExample(example: string): string {
  if ((getLibraryConfig().framework ?? "angular") !== "react") return example;
  return example.replace(/^\[([^\]]+)\]="(.*)"$/, "$1={$2}").replace(/^\(([^)]+)\)=".*"$/, "$1={handler}");
}

function renderInputsTable(inputs: StrictComponentAPI["availableInputs"]): string {
  if (inputs.length === 0) return `*This component has NO inputs.*\n\n`;
  let out = `| Input | Type | Required | Default | Example |\n`;
  out += `|-------|------|----------|---------|--------|\n`;
  for (const input of inputs) {
    const req = input.required ? "YES" : "no";
    const def = input.defaultValue || "-";
    out += `| \`${input.name}\` | \`${fmtType(input.type, input.typeResolved)}\` | ${req} | ${def} | \`${frameworkizeExample(input.example)}\` |\n`;
  }
  out += `\n`;
  return out;
}

function renderOutputsTable(outputs: StrictComponentAPI["availableOutputs"]): string {
  if (outputs.length === 0) return `*This component has NO outputs.*\n\n`;
  let out = `| Output | Event Type | Example |\n`;
  out += `|--------|------------|--------|\n`;
  for (const output of outputs) {
    out += `| \`${output.name}\` | \`${fmtType(output.eventType, output.eventTypeResolved)}\` | \`${frameworkizeExample(output.example)}\` |\n`;
  }
  out += `\n`;
  return out;
}

function renderDirectivesSection(
  directives: DirectiveEntry[],
  inheritanceMap?: Record<
    string,
    { baseClass?: string; inheritedInputs: readonly any[]; inheritedOutputs: readonly any[] }
  >,
): string {
  if (directives.length === 0) return "";
  let out = `## Directives\n\n`;
  for (const { analysis: dir, api } of directives) {
    out += `### ${api.selector}\n`;
    out += `**Class:** \`${api.className}\``;
    if (dir.metadata.standalone !== undefined) {
      out += ` | **Standalone:** ${dir.metadata.standalone ? "yes" : "no"}`;
    }
    out += `\n\n`;

    out += `#### Inputs (${api.availableInputs.length})\n\n`;
    out +=
      api.availableInputs.length === 0 ? `*This directive has NO inputs.*\n\n` : renderInputsTable(api.availableInputs);

    const dirInheritance = inheritanceMap?.[api.className];
    if (dirInheritance?.inheritedInputs.length) {
      out += `#### Inherited Inputs (from ${dirInheritance.baseClass || "base class"}) (${dirInheritance.inheritedInputs.length})\n\n`;
      out += `| Input | Type | Required | Description |\n|-------|------|----------|-------------|\n`;
      for (const input of dirInheritance.inheritedInputs) {
        out += `| \`${input.name}\` | \`${fmtType(input.type, input.typeResolved)}\` | ${input.required ? "YES" : ""} | ${input.description || "-"} |\n`;
      }
      out += `\n`;
    }

    out += `#### Outputs (${api.availableOutputs.length})\n\n`;
    out +=
      api.availableOutputs.length === 0
        ? `*This directive has NO outputs.*\n\n`
        : renderOutputsTable(api.availableOutputs);

    if (dirInheritance?.inheritedOutputs.length) {
      out += `#### Inherited Outputs (from ${dirInheritance.baseClass || "base class"}) (${dirInheritance.inheritedOutputs.length})\n\n`;
      out += `| Output | Event Type | Description |\n|--------|------------|-------------|\n`;
      for (const output of dirInheritance.inheritedOutputs) {
        out += `| \`${output.name}\` | \`${fmtType(output.eventType, output.eventTypeResolved)}\` | ${output.description || "-"} |\n`;
      }
      out += `\n`;
    }

    if (dir.publicMethods && dir.publicMethods.length > 0) {
      out += `#### Public Methods\n\n`;
      for (const method of dir.publicMethods) {
        const params = method.parameters
          .map((p) => `${p.name}${p.optional ? "?" : ""}: ${fmtType(p.type, p.typeResolved)}`)
          .join(", ");
        const asyncPrefix = method.isAsync ? "async " : "";
        out += `- \`${asyncPrefix}${method.name}(${params}): ${fmtType(method.returnType, method.returnTypeResolved)}\`\n`;
      }
      out += `\n`;
    }

    if (dir.dependencies && dir.dependencies.length > 0) {
      out += `#### Dependencies\n\n`;
      for (const dep of dir.dependencies) {
        const token = dep.injectionToken ? ` (${dep.injectionToken})` : "";
        out += `- \`${dep.name}: ${fmtType(dep.type, dep.typeResolved)}\`${token}\n`;
      }
      out += `\n`;
    }
  }
  return out;
}

function renderPipesSection(pipes: FileAnalysis["pipes"]): string {
  if (pipes.length === 0) return "";
  let out = `## Pipes\n\n`;
  out += `| Pipe | Class | Transform | Pure | Standalone |\n`;
  out += `|------|-------|-----------|------|------------|\n`;
  for (const pipe of pipes) {
    const params =
      pipe.transformMethod?.parameters
        .map((p) => `${p.name}${p.optional ? "?" : ""}: ${fmtType(p.type, p.typeResolved)}`)
        .join(", ") || "value: unknown";
    const returnType = fmtType(pipe.transformMethod?.returnType ?? null, pipe.transformMethod?.returnTypeResolved);
    out += `| \`${pipe.pipeName}\` | \`${pipe.className}\` | \`(${params}) → ${returnType}\` | ${pipe.pure ? "yes" : "no"} | ${
      pipe.standalone ? "yes" : "no"
    } |\n`;
  }
  out += `\n`;
  return out;
}

// ── Response helpers ──────────────────────────────────────────────

export function jsonResponse(data: unknown) {
  return { content: [{ type: "text" as const, text: JSON.stringify(data, null, 2) }] };
}

export function textResponse(text: string) {
  return { content: [{ type: "text" as const, text }] };
}

export function errorResponse(message: string) {
  return { content: [{ type: "text" as const, text: message }], isError: true as const };
}

export function requireComponent(
  componentName: string,
): { error: ReturnType<typeof errorResponse> } | { resolved: string; matchedSelector?: string } {
  const result = resolveComponentName(componentName);

  if ("resolved" in result) {
    return { resolved: result.resolved, matchedSelector: result.matchedSelector };
  }

  if ("suggestions" in result) {
    return {
      error: errorResponse(
        `Component "${componentName}" not found. Did you mean one of these?\n${result.suggestions
          .map((s) => `  - ${s}`)
          .join("\n")}\n\nUse the exact component name from the list above.`,
      ),
    };
  }

  return { error: errorResponse(result.error) };
}

// ── Detail-level handlers ───────────────────────────────────────────

export function handleComponentApi(componentName: string, selectorFilter?: string) {
  const analyses = getComponentAnalysis(componentName);

  let strictAPIs: StrictComponentAPI[] = [];
  for (const fileAnalysis of analyses) {
    for (const component of fileAnalysis.components) {
      strictAPIs.push(buildStrictAPIFromAnalysis(component));
    }
  }

  if (selectorFilter) {
    strictAPIs = strictAPIs.filter((api) => api.selector === selectorFilter);
  }

  const preloadedEntry = getAnalyzedEntry(componentName);
  const inheritanceMap = preloadedEntry?.inheritance || {};

  const MULTI_SELECTOR_THRESHOLD = 3;
  if (!selectorFilter && strictAPIs.length >= MULTI_SELECTOR_THRESHOLD) {
    let idx = `# ${componentName} — ${strictAPIs.length} sub-components\n\n`;
    idx += `**Import:** \`${getImportPath(componentName)}\`\n\n`;

    idx += `| Selector | Class | Own Inputs | Own Outputs |\n`;
    idx += `|----------|-------|------------|-------------|\n`;
    for (const api of strictAPIs) {
      idx += `| \`<${api.selector}>\` | \`${api.className}\` | ${api.availableInputs.length} | ${api.availableOutputs.length} |\n`;
    }
    idx += `\n`;

    const firstInheritance = Object.values(inheritanceMap).find((inh) => inh.inheritedInputs.length > 0);
    if (firstInheritance) {
      idx += `**Shared inputs** (from ${firstInheritance.baseClass || "base class"}): ${firstInheritance.inheritedInputs
        .map((i) => `\`${i.name}\`: ${fmtType(i.type, i.typeResolved)}`)
        .join(", ")}\n\n`;
    }

    idx += `Use \`get_component\` with a specific selector (e.g. \`${strictAPIs[0].selector}\`) for full API details.\n`;
    return textResponse(idx);
  }

  const displayName = selectorFilter ? `<${selectorFilter}>` : componentName;
  let result = `# API Reference: ${displayName}\n\n`;
  result += `**Import:** \`${getImportPath(componentName)}\`\n\n`;
  result += `---\n\n`;
  result += `## IMPORTANT: Use ONLY the inputs/outputs listed below.\n`;
  result += `Do NOT assume common properties like \`label\`, \`name\`, \`title\` etc. unless explicitly listed.\n\n`;

  for (const api of strictAPIs) {
    result += `## <${api.selector}>\n\n`;
    result += `**Class:** \`${api.className}\`\n\n`;

    if (preloadedEntry?.deprecation) {
      result += `### DEPRECATED\n`;
      if (preloadedEntry.deprecation.reason) result += `${preloadedEntry.deprecation.reason}\n`;
      if (preloadedEntry.deprecation.replacement)
        result += `Use \`${preloadedEntry.deprecation.replacement}\` instead.\n`;
      result += `\n`;
    }

    result += `### Available Inputs (${api.availableInputs.length})\n\n`;
    result += renderInputsTable(api.availableInputs);

    const apiInheritance = inheritanceMap[api.className];
    if (apiInheritance?.inheritedInputs.length) {
      result += `### Inherited Inputs (from ${apiInheritance.baseClass || "base class"}) (${apiInheritance.inheritedInputs.length})\n\n`;
      result += `| Input | Type | Required | Description |\n|-------|------|----------|-------------|\n`;
      for (const input of apiInheritance.inheritedInputs) {
        result += `| \`${input.name}\` | \`${fmtType(input.type, input.typeResolved)}\` | ${input.required ? "YES" : ""} | ${input.description || "-"} |\n`;
      }
      result += `\n`;
    }

    result += `### Available Outputs (${api.availableOutputs.length})\n\n`;
    result += renderOutputsTable(api.availableOutputs);

    if (apiInheritance?.inheritedOutputs.length) {
      result += `### Inherited Outputs (from ${apiInheritance.baseClass || "base class"}) (${apiInheritance.inheritedOutputs.length})\n\n`;
      result += `| Output | Event Type | Description |\n|--------|------------|-------------|\n`;
      for (const output of apiInheritance.inheritedOutputs) {
        result += `| \`${output.name}\` | \`${fmtType(output.eventType, output.eventTypeResolved)}\` | ${output.description || "-"} |\n`;
      }
      result += `\n`;
    }

    if (preloadedEntry?.contentProjection && preloadedEntry.contentProjection.length > 0) {
      result += `### Content Projection Slots\n\n`;
      for (const slot of preloadedEntry.contentProjection) {
        result += `- **${slot.name}**`;
        if (slot.selector) result += ` (select="${slot.selector}")`;
        result += `\n`;
      }
      result += `\n`;
    }

    if (api.requiredProviders.length > 0) {
      result += `### Required Providers\n\n`;
      for (const provider of api.requiredProviders) {
        result += `- \`${provider}\`\n`;
      }
      result += `\n`;
    }
  }

  result += renderDirectivesSection(collectDirectives(analyses), inheritanceMap);
  result += renderPipesSection(collectPipes(analyses));

  return textResponse(result);
}

export function handleComponentFull(componentName: string) {
  const preloaded = getPreloadedComponentMetadata(componentName);
  if (!preloaded) return errorResponse("Error: Metadata not loaded");
  if (preloaded.kind !== "analyzed") {
    return errorResponse(`Component "${componentName}" was not analyzed (kind=${preloaded.kind}): ${preloaded.reason}`);
  }

  let result = `# Deep Dive: ${componentName}\n\n`;
  result += `**Import:** \`${getImportPath(componentName)}\`\n\n`;

  if (preloaded.llmSummary) {
    result += `## Summary\n${preloaded.llmSummary}\n\n`;
  }

  const analyses = getComponentAnalysis(componentName);
  const allStrictAPIs: StrictComponentAPI[] = [];
  for (const fileAnalysis of analyses) {
    for (const component of fileAnalysis.components) {
      allStrictAPIs.push(buildStrictAPIFromAnalysis(component));
    }
  }

  if (allStrictAPIs.length > 0) {
    result += `## IMPORTANT: Use ONLY the inputs/outputs listed below.\n\n`;

    for (const api of allStrictAPIs) {
      result += `## <${api.selector}>\n\n`;
      result += `**Class:** \`${api.className}\`\n\n`;

      if (preloaded.deprecation) {
        result += `### DEPRECATED\n`;
        if (preloaded.deprecation.reason) result += `**Reason:** ${preloaded.deprecation.reason}\n`;
        if (preloaded.deprecation.since) result += `**Since:** v${preloaded.deprecation.since}\n`;
        if (preloaded.deprecation.replacement) result += `**Use instead:** ${preloaded.deprecation.replacement}\n`;
        result += `\n`;
      }

      result += `### Available Inputs (${api.availableInputs.length})\n\n`;
      result += renderInputsTable(api.availableInputs);

      const fullApiInheritance = preloaded.inheritance?.[api.className];
      if (fullApiInheritance?.inheritedInputs.length) {
        result += `### Inherited Inputs (from ${fullApiInheritance.baseClass || "base class"}) (${fullApiInheritance.inheritedInputs.length})\n\n`;
        result += `| Input | Type | Required | Description |\n|-------|------|----------|-------------|\n`;
        for (const input of fullApiInheritance.inheritedInputs) {
          result += `| \`${input.name}\` | \`${fmtType(input.type, input.typeResolved)}\` | ${input.required ? "YES" : ""} | ${input.description || "-"} |\n`;
        }
        result += `\n`;
      }

      result += `### Available Outputs (${api.availableOutputs.length})\n\n`;
      result += renderOutputsTable(api.availableOutputs);

      if (fullApiInheritance?.inheritedOutputs.length) {
        result += `### Inherited Outputs (from ${fullApiInheritance.baseClass || "base class"}) (${fullApiInheritance.inheritedOutputs.length})\n\n`;
        result += `| Output | Event Type | Description |\n|--------|------------|-------------|\n`;
        for (const output of fullApiInheritance.inheritedOutputs) {
          result += `| \`${output.name}\` | \`${fmtType(output.eventType, output.eventTypeResolved)}\` | ${output.description || "-"} |\n`;
        }
        result += `\n`;
      }

      if (preloaded.contentProjection && preloaded.contentProjection.length > 0) {
        result += `### Content Projection Slots\n\n`;
        for (const slot of preloaded.contentProjection) {
          result += `- **${slot.name}**`;
          if (slot.selector) result += ` (select="${slot.selector}")`;
          result += `\n`;
        }
        result += `\n`;
      }

      if (api.requiredProviders.length > 0) {
        result += `### Required Providers\n\n`;
        for (const provider of api.requiredProviders) {
          result += `- \`${provider}\`\n`;
        }
        result += `\n`;
      }
    }

    result += `---\n\n`;
  }

  result += renderDirectivesSection(collectDirectives(analyses), preloaded.inheritance);
  result += renderPipesSection(collectPipes(analyses));

  if (preloaded.inheritance && Object.keys(preloaded.inheritance).length > 0) {
    result += `## Inheritance\n\n`;
    for (const [className, inh] of Object.entries(preloaded.inheritance)) {
      result += `**${className}** extends \`${inh.baseClass}\``;
      if (inh.baseClassPath) result += ` (\`${inh.baseClassPath}\`)`;
      result += `\n`;
    }
    result += `\n`;
  }

  if (preloaded.configTokens && preloaded.configTokens.length > 0) {
    result += `## Config Tokens\n\n`;
    for (const token of preloaded.configTokens) {
      if (token.kind === "with-config") {
        result += `### Global config key: \`${token.configKey}\` (@WithConfig)\n`;
        result += `**Component:** \`${token.interface}\`\n\n`;
      } else {
        result += `### ${token.token}\n`;
        result += `**Interface:** \`${token.interface}\`\n\n`;
      }
      result += `| Property | Type | Optional | Description |\n|----------|------|----------|-------------|\n`;
      for (const prop of token.properties) {
        result += `| \`${prop.name}\` | \`${fmtType(prop.type, prop.typeResolved)}\` | ${prop.optional ? "YES" : ""} | ${prop.description || "-"} |\n`;
      }
      result += `\n`;
      if (token.defaultValues) {
        result += `**Defaults:**\n\`\`\`json\n${JSON.stringify(token.defaultValues, null, 2)}\n\`\`\`\n\n`;
      }
      if (token.kind === "with-config") {
        result += `**Global config usage:** these inputs fall back to the global config when not bound in the template:\n`;
        result += `\`\`\`typescript\nprovideNzConfig({ ${token.configKey}: { ${token.properties[0]?.name ?? "..."}: /* value */ } })\n\`\`\`\n\n`;
      } else {
        result += `**Provider usage:**\n\`\`\`typescript\nproviders: [{ provide: ${token.token}, useValue: { ...config } }]\n\`\`\`\n\n`;
      }
    }
  }

  if (preloaded.relatedComponents && preloaded.relatedComponents.length > 0) {
    result += `## Related Components\n\n`;
    for (const rel of preloaded.relatedComponents) {
      result += `- **${rel.name}** (${rel.relationship}): ${rel.reason}\n`;
    }
    result += `\n`;
  }

  if (
    (preloaded.importedBy && preloaded.importedBy.length > 0) ||
    (preloaded.importsFrom && preloaded.importsFrom.length > 0)
  ) {
    result += `## Dependency Graph\n\n`;
    if (preloaded.importsFrom && preloaded.importsFrom.length > 0)
      result += `**Imports from:** ${preloaded.importsFrom.join(", ")}\n`;
    if (preloaded.importedBy && preloaded.importedBy.length > 0)
      result += `**Imported by:** ${preloaded.importedBy.join(", ")}\n`;
    result += `\n`;
  }

  if (preloaded.commonPatterns && preloaded.commonPatterns.length > 0) {
    result += `## Usage Patterns\n\n`;
    for (const pattern of preloaded.commonPatterns) {
      result += `- ${pattern}\n`;
    }
    result += `\n`;
  }

  if (preloaded.readme) {
    result += `## README\n\n${preloaded.readme}\n\n`;
  }

  return textResponse(result);
}

export function handleComponentExamples(componentName: string) {
  const preloaded = getPreloadedComponentMetadata(componentName);
  if (!preloaded) return errorResponse("Error: Metadata not loaded");
  if (preloaded.kind !== "analyzed") {
    return errorResponse(`Component "${componentName}" was not analyzed (kind=${preloaded.kind}): ${preloaded.reason}`);
  }

  let result = `# Usage Patterns: ${componentName}\n\n`;

  if (preloaded.examples.length > 0) {
    result += `## Curated Examples\n\n`;
    for (const example of preloaded.examples) {
      result += `### ${example.name}: ${example.description}\n\n`;
      if (example.template) result += `\`\`\`html\n${example.template}\n\`\`\`\n\n`;
      if (example.typescript) result += `\`\`\`typescript\n${example.typescript}\n\`\`\`\n\n`;
    }
  }

  if (preloaded.storybookExamples && preloaded.storybookExamples.length > 0) {
    result += `## Storybook Examples (auto-extracted)\n\n`;
    for (const story of preloaded.storybookExamples) {
      result += `### ${story.storyName}\n\n\`\`\`html\n${story.template}\n\`\`\`\n\n`;
      if (Object.keys(story.args).length > 0) result += `**Default args:** ${JSON.stringify(story.args)}\n`;
      if (story.argTypes) {
        for (const [argName, argType] of Object.entries(story.argTypes)) {
          if (argType.options) result += `**${argName} options:** ${argType.options.join(", ")}\n`;
        }
      }
      result += `\n`;
    }
  }

  if (preloaded.commonPatterns && preloaded.commonPatterns.length > 0) {
    result += `## Common Patterns\n\n`;
    for (const pattern of preloaded.commonPatterns) result += `- ${pattern}\n`;
    result += `\n`;
  }

  if (preloaded.relatedComponents && preloaded.relatedComponents.length > 0) {
    result += `## Related Components\n\n`;
    for (const rel of preloaded.relatedComponents) result += `- **${rel.name}** (${rel.relationship}): ${rel.reason}\n`;
    result += `\n`;
  }

  if (preloaded.configTokens && preloaded.configTokens.length > 0) {
    result += `## Configuration\n\n`;
    for (const token of preloaded.configTokens) {
      if (token.kind === "with-config") {
        result += `Inputs of \`${token.interface}\` marked @WithConfig fall back to the global config key \`${token.configKey}\` (${token.properties.map((p) => p.name).join(", ")}).\n`;
        if (token.defaultValues) result += `Defaults: \`${JSON.stringify(token.defaultValues)}\`\n`;
        result += `\`\`\`typescript\nprovideNzConfig({ ${token.configKey}: { ...config } })\n\`\`\`\n`;
      } else {
        result += `Use \`${token.token}\` InjectionToken with interface \`${token.interface}\` to configure.\n`;
        if (token.defaultValues) result += `Defaults: \`${JSON.stringify(token.defaultValues)}\`\n`;
        result += `\`\`\`typescript\nproviders: [{ provide: ${token.token}, useValue: { ...config } }]\n\`\`\`\n`;
      }
    }
    result += `\n`;
  }

  return textResponse(result);
}

export function handleComponentTypes(componentName: string, selectorFilter?: string) {
  const analyses = getComponentAnalysis(componentName);
  const displayName = selectorFilter ? `<${selectorFilter}>` : componentName;
  let result = `# Types: ${displayName}\n\n`;
  result += `**Import:** \`${getImportPath(componentName).replace("{ ... }", "TypeName")}\`\n\n`;

  const allTypes: Array<{ name: string; kind: string; definition: string }> = [];

  for (const fileAnalysis of analyses) {
    allTypes.push(...fileAnalysis.exportedTypes);
    for (const component of fileAnalysis.components) {
      if (selectorFilter && component.metadata.selector !== selectorFilter) continue;
      allTypes.push(...component.exportedTypes);
    }
    for (const directive of fileAnalysis.directives || []) {
      allTypes.push(...directive.exportedTypes);
    }
  }

  if (allTypes.length === 0) {
    result += `*No exported types found in this component.*\n`;
  } else {
    for (const type of allTypes) {
      result += `## ${type.kind} ${type.name}\n\n\`\`\`typescript\n${type.definition}\n\`\`\`\n\n`;
    }
  }

  return textResponse(result);
}

// ── Search result formatting ──────────────────────────────────────

export function formatSelectorHints(selectors: string[], match: SearchResult): string {
  if (match.matchedSelector) {
    let hints = `**Matched Selector:** \`<${match.matchedSelector}>\` → use \`get_component("${match.matchedSelector}")\` for full API\n`;
    const otherSelectors = selectors.filter((s) => s !== match.matchedSelector);
    if (otherSelectors.length > 0)
      hints += `**Other Selectors:** ${otherSelectors.map((s) => `\`<${s}>\``).join(", ")}\n`;
    return hints;
  }

  if (selectors.length === 1)
    return `**Selector:** \`<${selectors[0]}>\` → use \`get_component("${selectors[0]}")\` for full API\n`;
  if (selectors.length > 1) return `**Selectors:** ${selectors.map((s) => `\`<${s}>\``).join(", ")}\n`;
  return "";
}

export function formatSearchResultEntry(match: SearchResult): string {
  const preloaded = getAnalyzedEntry(match.name);
  const selectors = extractSelectors(preloaded);
  const { directives, pipes } = countDirectivesAndPipes(preloaded);

  let section = `## ${match.name}`;
  if (preloaded?.deprecation) section += ` (DEPRECATED)`;
  section += `\n`;

  section += formatSelectorHints(selectors, match);
  section += `**Match:** ${match.reasons.join(", ")} (score: ${match.score})\n`;

  if (preloaded?.llmSummary) {
    section += `**Summary:** ${preloaded.llmSummary}`;
    if (directives > 0 || pipes > 0) {
      const parts: string[] = [];
      if (directives > 0) parts.push(`${directives} directive${directives !== 1 ? "s" : ""}`);
      if (pipes > 0) parts.push(`${pipes} pipe${pipes !== 1 ? "s" : ""}`);
      section += ` (+ ${parts.join(", ")})`;
    }
    section += `\n`;
  }

  const basicExample = preloaded?.examples?.find((e) => e.name === "basic");
  if (basicExample?.template) section += `\n\`\`\`html\n${basicExample.template}\n\`\`\`\n`;
  section += `\n---\n\n`;
  return section;
}

export function formatSearchFooter(topResults: SearchResult[]): string {
  const exampleSelectors = topResults
    .filter((m) => m.matchedSelector)
    .map((m) => `\`${m.matchedSelector}\``)
    .slice(0, 3);
  const selectorHint =
    exampleSelectors.length > 0 ? `e.g. ${exampleSelectors.join(", ")}` : `e.g. a component selector`;
  return `Use \`get_component\` with the **selector** (${selectorHint}) for full API details.\n`;
}

export function handleComponentSearch(query: string, components: string[]): ReturnType<typeof textResponse> {
  const metadataMap = buildSearchMetadataMap(components);
  const options = getSearchOptions();
  const scored = searchComponents(query, components, metadataMap, options);
  const topResults = scored.slice(0, 5);

  if (topResults.length === 0) {
    return textResponse(
      `No components found for "${query}".\n\nTry more specific terms.\n\nAll components:\n${components.join(", ")}`,
    );
  }

  let result = `# Search Results for "${query}"\n\n`;
  for (const match of topResults) result += formatSearchResultEntry(match);
  result += formatSearchFooter(topResults);

  return textResponse(result);
}

export function handleComponentListing(components: string[], listAll?: boolean): ReturnType<typeof textResponse> {
  let result = `# Available Components (${components.length})\n\n`;

  for (const compName of components) {
    const preloaded = getAnalyzedEntry(compName);
    const selectors = extractSelectors(preloaded);
    const { directives, pipes } = countDirectivesAndPipes(preloaded);

    result += `- **${compName}**`;
    if (selectors.length === 1) result += ` \`<${selectors[0]}>\``;
    else if (selectors.length > 1) result += ` ${selectors.map((s) => `\`<${s}>\``).join(", ")}`;
    if (directives > 0 || pipes > 0) {
      const parts: string[] = [];
      if (directives > 0) parts.push(`${directives} directive${directives !== 1 ? "s" : ""}`);
      if (pipes > 0) parts.push(`${pipes} pipe${pipes !== 1 ? "s" : ""}`);
      result += ` (+ ${parts.join(", ")})`;
    }
    if (preloaded?.deprecation) result += ` (DEPRECATED)`;
    if (preloaded?.llmSummary && !listAll) result += ` — ${preloaded.llmSummary}`;
    result += `\n`;
  }

  result += `\nUse \`get_component\` for full details on any component.\n`;
  return textResponse(result);
}
